Creation of language Spanish
enen92/screensaver.kaster pull request #3
Opened 2018-02-13 21:41 UTC by roliverosc

Hello @enen92 I have allowed myself to create the Spanish translation for your screensaver. I hope you like it and that you approve it.

Regards.

2018-02-13 23:51 UTC, enen92 requested changes
Thanks. Can you make the requested changes?

2018-02-13 23:51 UTC, enen92 commented on resources/language/resource.language.es_es/strings.po
> +msgstr ""
Missing

2018-02-13 23:51 UTC, enen92 commented on addon.xml
> +		<description lang="es_SP">Muestra bellas imágenes como las del protector de pantalla de chromecast. También puede mostrar sus propias fotos junto con su respectiva información.</description>
This should be es_es

2018-02-13 23:51 UTC, enen92 commented on addon.xml
> +		<summary lang="es_SP">Un protector de pantalla tipo Chromecast para Kodi</summary>
This should be es_es

2018-02-13 23:51 UTC, enen92 commented on addon.xml
> +			- Animations
Please drop this change as it refers to changes between versions. It will be changed in the next update

2018-02-13 23:51 UTC, enen92 commented on addon.xml
> +		<summary lang="es_SP">Un protector de pantalla tipo Chromecast para Kodi</summary>
es_ES

2018-02-13 23:51 UTC, enen92 commented on addon.xml
> +		<description lang="es_SP">Muestra bellas imágenes como las del protector de pantalla de chromecast. También puede mostrar sus propias fotos junto con su respectiva información.</description>
es_ES

2018-02-13 23:51 UTC, enen92 commented on resources/language/resource.language.es_es/strings.po
> +"Language-Team: English (http://www.transifex.com/projects/p/xbmc-addons/language/en/)\n"
Please adapt this entry

2018-02-14 09:46 UTC, roliverosc commented on addon.xml
> +		<summary lang="es_SP">Un protector de pantalla tipo Chromecast para Kodi</summary>
Sorry, I've already changed it.

2018-02-14 11:04 UTC, roliverosc commented
I've already changed it

2018-02-14 11:12 UTC, roliverosc commented
Already I've already changed all

2018-02-14 17:36 UTC, enen92 approved these changes

2018-02-14 17:36 UTC, merged